version: '3'

services:
  video_library:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./video_library:/video_library
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./video_library:/video_library:/.env
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./video_library:/video_library:/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A video_library worker --beat --loglevel=info
    volumes:
      - ./video_library:/video_library
    env_file:
      - ./video_library:/video_library:/.env
    depends_on:
      - db
      - redis
      - app

volumes:
  pgdata: