# Generated by Django 4.1.7 on 2023-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
